spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/orders_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

kafka:
  bootstrap-servers: kafka:9092

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

outbox:
  retention-hours: 24
  cleanup-interval-ms: 3600000

connect:
  url: http://kafka-connect-1:8083
  connector-names:
    - debezium-orders-outbox

management:
  endpoint:
    health:
      show-details: always